version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pocket-fashion-backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build: ./frontend
    container_name: pocket-fashion-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT:-8000}
    depends_on:
      - backend
    command: npm start